#!/bin/bash

# Stop on failure
set -e

# remove any stale documentation files
rm -rf doc/_build

# Build module and documentaiton
pushd src
make clean
make
popd
pushd test
make clean
make
popd
pushd doc
make html
make latexpdf
make epub
markdown  ReleaseNotes.md >ReleaseNotes.html
popd

# Set up a dist folder
rm -rf dist
mkdir -p dist/doc/html
cp src/ladybug.mod dist/
cp test/lb-test.mod dist/
cp -R doc/_build/html dist/doc/
cp doc/_build/latex/ladybug.pdf dist/doc
cp doc/_build/epub/ladybug.epub dist/doc
cp doc/ReleaseNotes.html dist/
mkdir dist/overlays
cp overlays/i41CX+-retina.png dist/overlays/

# Clean up some stuff we do not want
rm -rf dist/doc/html/_sources
rm dist/doc/html/.buildinfo

# Pack a .zip
pushd dist
zip -r ladybug *
popd
