(define memories
  '((memory Ladybug1 (position independent)
            (bank 1) (address (#x0 . #xFFF))
            (section (FAT #x0) Code Code1 (CodeQ0 (#x0 . #x3FF))
                     (Legal7 #xCDD)
                     (CodeF00 #xF00)
                     (KeyTable #xC00) (Tail #xFBF))
            (checksum #xFFF hp41)
            (fill 0))
    (memory Ladybug2 (position independent)
            (bank 2) (address (#x0 . #xFFF))
            (section (Bank2Header #x0) Code2 (Tail2 #xFF4))
            (checksum #xFFF hp41)
            (fill 0))
    (memory OS4 (bank 1) (address (#x4000 . #x4FFF))
            (section (Header4 #x4000) OSCode)
            (checksum #x4FFF hp41)
            (fill 0))))
